Storage: Add missing conversion of last counter
In theory this should get rid of an `OverflowError` I noticed when
running `measure.t` using NumPy 2.1:

   lost_messages += (counter - last_counter) % 256 - 1
                    ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
   OverflowError: Python integer 256 out of bounds for uint8